spring:
  config:
    import: optional:consul:localhost:8500

  cloud:
    consul:
      host: localhost
      port: 8500


thread:
  pool:
    corePoolSize: 2
    maxPoolSize: 24
    keepAliveSeconds: 30
    queueCapacity: 200