spring:
  config:
    import: optional:consul:localhost:8500
#  datasource:
#    url: jdbc:mysql://localhost:3306/wq_ems?useUnicode=true&allowMultiQueries=true&useAffectedRows=true&characterEncoding=utf8&serverTimezone=UTC
#    username: root
#    password: 123456
  #    url: jdbc:mysql://39.100.84.102:3306/wq_ems?useUnicode=true&allowMultiQueries=true&useAffectedRows=true&characterEncoding=utf8&serverTimezone=UTC
  #    username: wq_ems
  #    password: BKZNs8BXx7bCp8se
  cloud:
    consul:
      host: localhost
      port: 8500


thread:
  pool:
    corePoolSize: 2
    maxPoolSize: 24
    keepAliveSeconds: 30
    queueCapacity: 200