server:
  port: 20001
  address: 0.0.0.0
spring:
  application:
    name: jhj-user-service
  profiles:
    active:
      - local
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: true #是否启用配置中心功能
        format: YAML #设置配置值的格式
        prefix: config #设置配置所在目录
        data-key: data #配置key的名字，由于Consul是K/V存储，配置存储在对应K的V中
        watch:
          # 是否开启自动刷新，默认值 true 开启
          enabled: true
          # 刷新频率，单位：毫秒，默认值 1000
          delay: 10000
      discovery: # 服务发现配置
        enabled: true
        register: true
        deregister: true
        prefer-ip-address: true
        health-check-interval: 10s
        health-check-critical-timeout: 30s
        health-check-path: /actuator/health
        instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}-${server.port} # 应用名称+服务器IP+端口+版本
      enabled: true
#  datasource:
#    url: jdbc:mysql://localhost:3306/wq_ems?useUnicode=true&allowMultiQueries=true&useAffectedRows=true&characterEncoding=utf8&serverTimezone=UTC
#    username: root
#    password: 123456
  #    url: jdbc:mysql://39.100.84.102:3306/wq_ems?useUnicode=true&allowMultiQueries=true&useAffectedRows=true&characterEncoding=utf8&serverTimezone=UTC
  #    username: wq_ems
  #    password: BKZNs8BXx7bCp8se




thread:
  pool:
    corePoolSize: 2
    maxPoolSize: 24
    keepAliveSeconds: 30
    queueCapacity: 200