server:
  port: 20000
  address: 0.0.0.0
#logging:
#  level:
#    root:  INFO
#    org.springframework:  INFO
#    com.jhj.gateway:  INFO
#    com.jhj:  INFO
management:
  endpoints:
    gateway:
      enabled: true
    web:
      exposure:
        include: gateway
spring:
  profiles:
    active:
      - local
  application:
    name: jhj-gateway-service
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: GMT+8
  cloud:
    gateway:
      httpclient:
        ssl:
          handshake-timeout-millis: 10000
          close-notify-flush-timeout-millis: 3000
          close-notify-read-timeout-millis: 0
          useInsecureTrustManager: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
        add-to-simple-url-handler-mapping: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: jhj-oss
          uri: lb://jhj-oss-service
#          filters:
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 50
#                redis-rate-limiter.burstCapacity: 100
#                key-resolver: "#{@hostAddrKeyResolver}"
          predicates:
            - Path=/oss/**



        - id: jhj-user
          uri: lb://jhj-user-service
          predicates:
            - Path=/user/**

    consul:
      config:
        enabled: true #是否启用配置中心功能
        format: YAML #设置配置值的格式
        prefix: config #设置配置所在目录
        data-key: data #配置key的名字，由于Consul是K/V存储，配置存储在对应K的V中
        watch:
          # 是否开启自动刷新，默认值 true 开启
          enabled: true
          # 刷新频率，单位：毫秒，默认值 1000
          delay: 10000
      discovery: # 服务发现配置
        enabled: true
        register: true
        deregister: true
        prefer-ip-address: true
        health-check-interval: 10s
        health-check-critical-timeout: 30s
        health-check-path: /actuator/health
        instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}-${server.port} # 应用名称+服务器IP+端口+版本
    enabled: true
  main:
    allow-bean-definition-overriding: true
#feign:
#  httpclient:
#    enabled: false
#  okhttp:
#    enabled: true
#  client:
#    config:
#      rpc-user: # feign name
#        requestInterceptors:
#          - com.jhj.common.Intercptor.FeignTokenInterceptor

exclusion:
  url:
#    - /ems/v2/api-docs
#    - /bi/v2/api-docs
#    - /rmp/v2/api-docs
#    - /ditui/v2/api-docs
#    - /oms/v2/api-docs
#    - /oss/v2/api-docs