spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wq_oss?useUnicode=true&allowMultiQueries=true&useAffectedRows=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
  config:
    import: optional:consul:localhost:8500
  cloud:
    consul:
      host: localhost
      port: 8500
exclusion:
  url:
    - /**

testpro:
  id: 1
  name: naemaa
  flag: true
  maps: {k1=k1, k2=k2}
  lists:
    - String1
    - String2
  dog:
    name: 旺财
    age: 2
thread:
  pool:
    corePoolSize: 2
    maxPoolSize: 24
    keepAliveSeconds: 30
    queueCapacity: 200